### ISSUE TITLE
Replace navigation links

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruption-email-alerts#13]
<img width="1037" alt="Screenshot 2020-04-27 at 10 27 29" src="https://user-images.githubusercontent.com/10854265/80356684-b3f3c200-8871-11ea-8bac-863a1bced4bc.png">

Title to read: "Manage alerts about disruptions"
Can you make this a H1 tag but use the H3 light class as an override, please?

**Comment by mrmjprice** [comment]
Can you also do this on sign up?:

#Sign up to email alerts about disruption

**Comment by rolorogan** [comment]
@mrmjprice Can you please confirm what the h3 light class is? Cannot find in design system
