### ISSUE TITLE
Confirm subscription email

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruption-email-alerts#27]
- [x] Remove Service bullet points
- [x] Change footer on the right-hand side: "Manage alerts or unsubscribe" (one link only) takes you to the preference centre
- [x] Sender name: "no reply" - change to "WMN Disruptions"
- [x] Sender email: can we change this to "noreply@wmnetwork.co.uk"?
- [x] Subject: "Confirm your subscription"

**Comment by rolorogan** [comment]
@mrmjprice We can't use the wmnetwork.co.uk as an email address at the moment but have opened a servicedesk to get it setup on Campaign Monitor

**Comment by mrmjprice** [comment]
Hi @Rippled - Can you tick the box and close this issue when "Sender email" is changed to noreply@wmnetwork.co.uk ?
